version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
